//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaBC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int codigo { get; set; }
        public int codigoEncabezado { get; set; }
        public int codigoProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual FacturaEncabezado FacturaEncabezado { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
