//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaBC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaEncabezado
    {
        public FacturaEncabezado()
        {
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
        }
    
        public int codigo { get; set; }
        public int codigoCliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
    }
}
